### ISSUE TITLE
'error: cannot lock ref' 

### ISSUE THREAD

**Issue by codeing999** [JeungHoSub/hanghae_node3week#18]
# 문제
error: cannot lock ref 'refs/remotes/origin/dev/jeunghosub': is at 1d959a02e6a712d4b3c74f124b37b40b08a95fb3 but expected 08118432b935058036a2e7b5e42f185196bffe3f    
From https://github.com/JeungHoSub/hanghae_node3week
 ! 0811843..d29d40e  dev/jeunghosub -> origin/dev/jeunghosub  (unable to update local ref)
PS C:\Users\jcl12\OneDrive\바탕 화면\projects\hanghae_node3week\src> git status
On branch submain
Your branch is behind 'origin/submain' by 8 commits, and can be fast-forwarded.
  (use "git pull" to update your local branc

**Comment by unchaptered** [comment]
해당 내용 읽어보면 `원인` 자체는 다양하게 많다고 하는데, 가장 쉬운 해결 방법은 git remote 를 제거하고 다시 연결하라고 하네요.

```cmd
git remote rm origin
git remote add origin https://github.com/JeungHoSub/hanghae_node3week.git
```

> References - [“error: cannot lock ref” – what to do?](https://linuxpip.org/git-error-cannot-lock-ref/#:~:text=%22error%3A%20cannot%20lock%20ref%22%20simply%20means%20information%20in%20%2F,cannot%20continue%20to%20create%20index.)


추가적으로 `Git Lock` 이라는 현상에 대해서도 찾아봤는데 MS Azure DevOps 사이트에 Git 관련된 공식 문서에서 해당 내용이 적혀 있는 걸 찾았습니다. 작성 날자가 `2022. 07. 20` 라고 있는데 아마 최근에 생긴 것인지 정확히 알 수는 없네요.

> References - [https://docs.microsoft.com/ko-kr/azure/devops/repos/git/lock-branches?view=azure-devops](https://docs.microsoft.com/ko-kr/azure/devops/repos/git/lock-branches?view=azure-devops)

**Comment by unchaptered** [comment]
![Uploading branches.png…]()

**Comment by unchaptered** [comment]
![branches](https://user-images.githubusercontent.com/86306802/183500084-9250a6eb-f881-4cb5-a60b-e5a054e467c0.png)
